name: IP Range Port Scanner

on:
  issues:
    types: [opened]

jobs:
  scan-range:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run IP Range Scanner
        id: range-scan
        run: |
          python ip_range_checker.py "${{ github.event.issue.body }}"
          python generate_html.py

      - name: Publish Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
