name: IP Scanner and HTML Generator

on:
  issues:
    types: [opened]

jobs:
  scan-and-generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Save Issue Body as Environment Variable
      id: save_body
      run: |
        echo "BODY<<EOF" >> $GITHUB_ENV
        echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Run IP Scanner
      run: python ip_scanner.py "$BODY"

    - name: Generate HTML Report
      run: python generate_html.py

    - name: Commit and Push Results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html scan_results.json
        git commit -m "Update scan results and HTML report"
        git push
